import type { Scenario, ScenarioFrame } from './scenarios';
function frame(
  title: string,
  note: string,
  p: string,
  m0: string,
  m1: string,
  g1: string,
  g2: string,
): ScenarioFrame {
  return {
    title,
    note,
    lanes: [
      { label: 'P0', value: p },
      { label: 'M0', value: m0 },
      { label: 'M1', value: m1 },
      { label: 'G1', value: g1 },
      { label: 'G2', value: g2 },
    ],
  };
}
const start = frame(
  'G1 正在执行',
  '假设 GOMAXPROCS=1；只有一个 P，但可以有不止一个操作系统线程。',
  '交给 M0',
  '运行 G1',
  '休眠',
  'running',
  'runnable',
);
export const schedulerScenarios: Scenario[] = [
  {
    id: 'netpoll',
    label: '可轮询网络 I/O',
    frames: [
      start,
      frame(
        'G1 等待网络数据',
        '支持网络轮询的 I/O 路径把 G 挂起；同一个 M 与 P 可以执行其他就绪 G。',
        '交给 M0',
        '运行 G2',
        '休眠',
        'waiting · 网络',
        'running',
      ),
      frame(
        '网络就绪，G1 可运行',
        '就绪事件使 G1 进入 runnable，不保证立即抢占当前 G2。',
        '交给 M0',
        '运行 G2',
        '休眠',
        'runnable',
        'running',
      ),
      frame(
        '调度器再次选择 G1',
        '这是一种可能的顺序。G1 不要求永远绑定之前的线程。',
        '交给 M0',
        '运行 G1',
        '休眠',
        'running',
        '已完成',
      ),
    ],
  },
  {
    id: 'syscall',
    label: '阻塞系统调用',
    frames: [
      start,
      frame(
        'M0 进入阻塞系统调用',
        '线程本身可能被内核阻塞。运行时为 P 的移交保留路径，不代表每次调用都必须新建线程。',
        '系统调用状态',
        '随 G1 阻塞',
        '休眠',
        'syscall',
        'runnable',
      ),
      frame(
        'P0 被交给 M1',
        '这里展示运行时回收 P 后让另一个可用 M 继续执行的路径。M0 不持有可执行 Go 代码的 P。',
        '交给 M1',
        '仍在系统调用',
        '运行 G2',
        'syscall',
        'running',
      ),
      frame(
        '系统调用返回',
        '若 M0 此时无法获得 P，G1 进入 runnable，M0 不能无 P 继续执行普通 Go 代码。',
        '交给 M1',
        '等待或休眠',
        '运行 G2',
        'runnable',
        'running',
      ),
      frame(
        'G1 在 M1 上继续',
        'G2 结束后，G1 被选中。实际调度也可能选择其他合法线程和时机。',
        '交给 M1',
        '休眠',
        '运行 G1',
        'running',
        '已完成',
      ),
    ],
  },
  {
    id: 'preempt',
    label: 'CPU 计算与抢占',
    frames: [
      start,
      frame(
        '发出抢占请求',
        '请求不是立即完成。运行时还需在安全点处理，不能把某个阈值解释为硬实时保证。',
        '交给 M0',
        '仍运行 G1',
        '休眠',
        'running · 请求待处理',
        'runnable',
      ),
      frame(
        '在安全点让出执行',
        'G1 重新变成可运行状态，M0 与 P0 可以转去执行 G2。',
        '交给 M0',
        '运行 G2',
        '休眠',
        'runnable',
        'running',
      ),
      frame(
        '稍后继续 G1',
        '抢占改善响应性与 GC 配合，不保证你的业务在固定时间内拿到 CPU。',
        '交给 M0',
        '运行 G1',
        '休眠',
        'running',
        '已完成',
      ),
    ],
  },
];
